# Generated by Django 2.2.9 on 2020-02-05 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_cell', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('regno', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('course', models.CharField(choices=[('Btech', 'Btech'), ('BBA', 'BBA'), ('B.J.M.C', 'B.J.M.C'), ('MTECH', 'MTECH')], max_length=254, null=True)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('Mechanical', 'Mechanical'), ('Electrical', 'EEE')], max_length=254)),
                ('phno', models.IntegerField(null=True)),
                ('parent_name', models.CharField(max_length=254, null=True)),
                ('parent_phno', models.IntegerField(null=True)),
                ('cgpa', models.IntegerField(default=0)),
                ('backlogs', models.IntegerField(default=0, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_cell.company')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
