# Generated by Django 2.2.9 on 2020-02-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='NP', max_length=50),
        ),
    ]
