# Generated by Django 2.2.9 on 2020-02-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('PLACED', 'PLACED'), ('NOT PLACED', 'NOT PLACED')], max_length=50),
        ),
    ]
