# Generated by Django 2.2.9 on 2020-02-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('comp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=50)),
                ('job_profile', models.CharField(choices=[('Technical', 'Technical'), ('Non Technical', 'Non Technical'), ('Both', 'Both')], max_length=254)),
                ('comp_status', models.CharField(choices=[('In process', 'In process'), ('Closed', 'Closed'), ('Coming soon', 'Coming soon')], max_length=254)),
            ],
            options={
                'verbose_name': 'Comapany',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
