# Generated by Django 2.2.9 on 2020-02-08 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_cell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_students', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_cell.company')),
            ],
        ),
    ]
