# Generated by Django 2.2.9 on 2020-02-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_cell', '0002_company_stud'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='no_of_students',
            field=models.IntegerField(default=0),
        ),
    ]
