# Generated by Django 2.2.9 on 2020-02-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_cell', '0003_company_no_of_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company_stud',
        ),
    ]
