# Generated by Django 2.2.9 on 2020-02-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_cell', '0004_delete_company_stud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='no_of_students',
            new_name='no_of_students_applied',
        ),
    ]
