# Generated by Django 2.2.9 on 2020-02-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_cell', '0006_company_image_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image_logo',
            field=models.ImageField(blank=True, upload_to='post-image'),
        ),
    ]
