# Generated by Django 2.2.9 on 2020-02-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_cell', '0007_auto_20200221_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image_logo',
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to='post-image/'),
        ),
    ]
