# Generated by Django 2.2.9 on 2020-02-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_cell', '0008_auto_20200221_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comp_status',
            field=models.CharField(max_length=254),
        ),
    ]
