# Generated by Django 2.2.9 on 2020-02-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_cell', '0009_auto_20200224_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comp_status',
            field=models.CharField(choices=[('In process', 'In process'), ('Closed', 'Closed'), ('Coming soon', 'Coming soon')], max_length=254),
        ),
    ]
